apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstream.fullname" . }}
  labels:
    {{- include "logstream.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logstream.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logstream.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.metricsPort }}"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: ingestor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          env:
            - name: MONGODB_URI
              value: {{ .Values.mongodb.uri | quote }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
            {{- if .Values.alerter.slackWebhook }}
            - name: SLACK_WEBHOOK
              value: {{ .Values.alerter.slackWebhook | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
